apiVersion: 1

datasources:
  - name: Sentinel-MySQL
    type: mysql
    access: proxy
    url: sentinel-db:3306
    database: sentinel_h2o_db
    user: sentinel_user
    secureJsonData:
      password: sentinel_password_2026
    isDefault: true
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: false

