; PlatformIO Project Configuration File for Sentinel-H2O Node
; I Concurso de Ciencia y Tecnologia para la Seguridad Hidrica - ANA / CRHCCH-H

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.11.0
    vshymanskyy/TinyGSM @ ^0.11.7

build_flags = 
    -D CORE_DEBUG_LEVEL=2
